# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trashgo', '0003_auto_20160917_1824'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bin',
            unique_together=set([]),
        ),
    ]
